### ISSUE TITLE
Remove github bot comments on PRs

### ISSUE THREAD

**Issue by maximusunc** [NCATS-Gamma/robokop-rewrite#113]
The email and comment spam is too much and once this gets merged back into the old repo, we don't want all watchers to get the spam. If something fails, you can still go look at the pipeline and see what went wrong.

**Comment by alongreyber** [comment]
The pipeline output doesn't contain the test results because they are stored in a file. How would you feel about using [artifacts](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts) to store the output of the build (test results + coverage + eslint)? I think that this is a good use case for it.

**Comment by maximusunc** [comment]
I feel like I can see all I need by just looking in the actions, so I think artifacts would just be something extra. But this is outside of this issue.

**Comment by maximusunc** [comment]
Oh I see the coverage. Yeah, that might be nice to have as an artifact. But make that a separate issue please. This is just for removing the bot comments.
