### ISSUE TITLE
Switch concepts and predicates over to biolink

### ISSUE THREAD

**Issue by maximusunc** [NCATS-Gamma/robokop-rewrite#50]
https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml

**Comment by alongreyber** [comment]
How do we want to include the biolink model? Should we get it as an API request to: [https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.yaml](https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.yaml) or directly add the yaml to the build?

API Request Advantages:
- Don't have to manually update the build files on new biolink versions
- Reduces bundle size

Build File Advantages:
- No possibility of a change to the yaml file breaking our application
- Easier to use because there is not API request

**Comment by patrickkwang** [comment]
A third option is to make an API request for a specific version (tag, commit) of this yaml file. Then it will be easier to update than a packaged file, and without the increased bundle size. There will also be no risk of sudden breakage. However, I don't love having to make this API call on every page load.

**Comment by maximusunc** [comment]
I don't know about the size of the predicates list, but we were getting concepts on initial load and then holding them in memory for everything to use. For predicates, we were making a separate call when opening an edge panel.

**Comment by alongreyber** [comment]
[This library](https://github.com/darkty2009/webpack-require-http#readme) loads an HTTP resource into the bundle at build time. Not sure if we want this library as a dependency but we might be able to pull out the code we need and do it this way.
